### ISSUE TITLE
Marking Definition Type property enforcement with the actual Marking Object

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#123]
Currently there are two marking objects (tlp and statement).  There is a enforcement in the spec that states that the Definition Type must be TLP if the marking object is the TLP object, and must be Statement if the marking object is the marking object.

It would be great if it was considered that the actual marking object have the Type information property as well.  This would provide two optimizations for implementation:

1. Have a Type property which must have the same value in the Marking Definition's "definition_type" property.  This is a simple validation that is dynamic.

2. and building on 1, to allow simpler custom implementations of marking objects: Anyone could add a custom marking object and all of the required validation logic can be part of the Marking object itself.  No modifications to a config or upstream code would be required.

**Comment by jordan2175** [comment]
We will look at this post working draft 04.

**Comment by jordan2175** [comment]
Rich P. will take a stab at this.

**Comment by jordan2175** [comment]
We talked about this on the 2019-06-11 working call.

**Comment by jmgnc** [comment]
two comments: all the TLS objects have been produced, so only statements will ever be produced from now on.  Also, there are other places in the spec that we have two option properties where ONE of the two must be present, and we do not require a third property to tell you which one is present.  so I'd recommend that we don't so we are consistent.

Allan also pointed out that it would require us to create new TLP objects, as the old ones would be incompatible w/ this change.

**Comment by rpiazza** [comment]
Hi @StephenOTT,

I read thru all of the comments above, and I'm still not sure what the issue is :-)

The value of the type property of any marking-definition object is _marking-definition_. What I think you want to do is have the value be the "kind" of marking-definition - e.g., _statement_, instead of having another property for that.   I think that would imply that to determine if a particular object is a marking-definition object, you need to keep track of all of type names that are used for marking-definition objects.  I'm not sure what that buys you.  

I'm not sure what "modifications to a config or upstream code" you have in mind.  Could you be more specific.

Please expand upon what issue you think the spec needs to solve and we will consider it for a future release.

**Comment by ejratl** [comment]
definition_type and definition have been deprecated. New marking types should be proposed as extensions.
