### ISSUE TITLE
Inconsistent implementation of boolean property names for 2.13.2​ ​Windows™ Process Extension

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#136]
the section `2.13.2​ ​Windows™ Process Extension` has two boolean properties: `aslr_enabled` and `dep_enabled`.  These props do not use the `is_` pattern used everywhere else in the COOs.

is there a reason for this?

**Comment by ejratl** [comment]
This is a great catch. This occurs in Version 2.0. If it gets changed for 2.1, then it would be a breaking change just for the sake of consistency. I would propose to let it slide and to add a check so that no more of these slip through. Would that be sufficient or are you proposing to change the names of these properties?

**Comment by ejratl** [comment]
I'm closing this issue. Please re-open if you would like to propose that it be changed in a future spec version as a breaking change.

**Comment by jordan2175** [comment]
Yeah, we missed that in the release of 2.0.  The TC has very little appetite for making this sort of breaking change.  Please feel free to bring it up on the email list.  If a majority of people agree, then we can easily make that change.  But my guess is that the TC will not want to make any more breaking changes unless they are actually needed.
