### ISSUE TITLE
Why does Network Traffic COO (and other COOs like Process COO) have circular reference: encapsulates_refs // encapsulated_by_ref?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#139]
Why does Network Traffic COO have circular reference: encapsulates_refs // encapsulated_by_ref?

Thanks

**Comment by StephenOTT** [comment]
Same with Process COO which has parent_ref and child_refs

Current thinking is original data design was to support objects that reference children or objects that reference parents.  (As both the fields are optional)

**Comment by rpiazza** [comment]
Hi @StephenOTT,

Both properties are optional because the spec doesn't want to make objects that only have one of "parent" or "child" refs invalid.  

I'm not sure I would characterize having both the parent and child ref properties as being "circular".  This is a standard way to modeling a tree structure.  Is there something about these properties that you think is problematic?

**Comment by StephenOTT** [comment]
@rpiazza it means that every child needs to be aware of its parent. It makes the code reuse problematic to create objects that can be found in different parents but are the same object child objects (type /instance)

If you are defining a tree structure with parents, and you model folder structures do something like symlinks not get picked up by your tree structure ?   If you have children without ref to parents, then multiple parents can point to the same children, and the query logic to find parents of a specific child becomes a search function. 

If you are going to tie all the children to a single parent then would it not make more sense to have a actual heiarchal structure within the json?  Why have a flat structure at that point?

**Comment by rpiazza** [comment]
@StephenOTT,
Each process needs to be its own object.  In STIX, relationships between objects are always made by using a reference to the object (there are various ways to do this).  Additionally, both parent and child refs properties are optional on purpose - since as I mentioned before, you want to be able to share incomplete information.  The parent of a process object one might want to share may not known, but you can still share it.

**Comment by ejratl** [comment]
@StephenOTT Can we close this issue or do you want more discussion on the topic? Thanks for raising the question.

**Comment by StephenOTT** [comment]
>Additionally, both parent and child refs properties are optional on purpose - since as I mentioned before, you want to be able to share incomplete information.

If this design was implemented to support incomplete information, then this explanation should be added into the spec as it has downstream planning implications for implementations of the spec and expectations of how data will be processed and used.

**Comment by jordan2175** [comment]
The SCOs in STIX 2.1 are now fully linkable inside a graph.  So just like SDOs, your storage and query solutions will need to be able to traverse a graph.
