### ISSUE TITLE
Should Optional properties that have default values that had their original object parsed with the default value still produce the value on re-print to Json? (re: Revoked)

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#150]
Looking at the SDO Revoked property, there is a case where Revoked is optional, as per the spec: Section 3.1 of the STIX Core Concepts.

And the default value is marked as "false".  So if someone does not provide this value, its then marked as false.

But does someone need to propagate this value?  

Consider something like:

```json
    {
      "type": "indicator",
      "id": "indicator--59ccb738-921a-4941-8ab2-33da522bd4e1",
      "created": "2019-04-08T22:59:50.0Z",
      "modified": "2019-04-08T22:59:50.00Z",
      "revoked": false,
      "labels": [
        "malicious-activity"
      ],
      "name": "128.0.0.1",
      "pattern": "[ipv4-addr:value = '128.0.0.1']",
      "valid_from": "2019-04-08T22:59:50.000Z"
    }
```

vs

```json
    {
      "type": "indicator",
      "id": "indicator--59ccb738-921a-4941-8ab2-33da522bd4e1",
      "created": "2019-04-08T22:59:50.0Z",
      "modified": "2019-04-08T22:59:50.00Z",
      "labels": [
        "malicious-activity"
      ],
      "name": "128.0.0.1",
      "pattern": "[ipv4-addr:value = '128.0.0.1']",
      "valid_from": "2019-04-08T22:59:50.000Z"
    }
```

The generic spec says that these should be equal... BUT from the standpoint of comparing Input vs output (and future signing of JSON), these two objects are not equal...

What is the direction for this issue?  This seems that revoked (and any other values of similar structure) should have their optional status removed, and made to be required?

**Comment by StephenOTT** [comment]
stix TC any direction on this?

**Comment by StephenOTT** [comment]
Update:

This appears to be a issue only in two places:

the Revoked property that is used across the bundleable objects, and the Sighting SRO in the summary property.


Here is a example workaround for future usage: https://github.com/StephenOTT/STIX-Java/blob/0.8.7/src/main/java/io/digitalstate/stix/common/StixBoolean.java

https://github.com/StephenOTT/STIX-Java/blob/0.8.7/src/main/java/io/digitalstate/stix/json/StixBooleanSerializer.java

**Comment by varnerac** [comment]
So `spec_version` is also affected by this. It's implicitly `2.0. What about numbers? In JSON I believe that `1`, `1.0` and `1.00` are the same number according to the spec. I don't want to get ahead of ourselves on the signatures because I don't know that it's figured out.

**Comment by StephenOTT** [comment]
Spec_version is listed as a "string" in the spec: core: section 5.1

**Comment by varnerac** [comment]
Sorry, should've said it's implicitly `"2.0"`. Same thing though... An object without a `spec_version` key is semantically no different than one with `"spec_version": "2.0"`. That's the same as no difference between an object with no `revoked` key and one with `revoked` explicitly set to `true`.

**Comment by StephenOTT** [comment]
My understanding would be that historically that would have been acceptable because the bundle is spec version bound. And the bundle is the only way to officially transmit data.  So everything in a bundle would be of my version of the spec. 

When I did the java impl I added spec version into every object so it can be propagated into other systems and keep its spec info. But given bundle is the wrapper for data transmission I can easily imagine the logic of above

**Comment by varnerac** [comment]
> My understanding would be that historically that would have been acceptable because the bundle is spec version bound. And the bundle is the only way to officially transmit data. So everything in a bundle would be of one version of the spec.

Yes. A `Bundle` with a `spec_version` can only have a `spec_version` of `"2.0"`. Everything in it is 2.0. However, we already know everything in it at an individual level is 2.0 because it has a `spec_version` of 2.0 or it doesn't have a `spec_version` and is implicitly 2.0. There was even weirder stuff going on in the TAXII 2 world when reading content type headers that will trigger me if I think too hard about it.
  
So, that _was_ the case. The 2.0 `Bundle` included a `spec_version` key. It's not present in `2.1`. So, if you're writing a library/server that works on 2.0 and 2.1, you don't really care about the `Bundle` `spec_version`. A 2.1 `Bundle` can have 2.0 and 2.1 objects. You know the spec version of each object based on the absence (implicitly `"2.0"`) or value of the `spec_version` key. But, like you, I explicitly store a version enumeration in my data store because I want the ability to query by version. I don't want jacked up query logic requiring me to handle a `null`. However, my implementation does not track whether the original message I received had an explicitly `spec_version` key or not. I don't know of anything in the spec now that explicitly forbids it. If it does, it's not the worst interoperability sin I could commit. I am hesitant to write code anticipating a future JSON signature solution because things change. `spec_version` in my case ends up being the same problem you point out with `revoked`. I don't think it's a problem now, or not a big problem if it is.

> When I did the java impl I added spec version into every object so it can be propagated into other systems and keep its spec info.

Samesies

> Or another way to say it: a object is only interpreted when it's in a bundle. A bundle dictates what version of the spec to interpret the objects as.

So, I don't think that's the case. In 2.1 an object can and must be interpreted on its own. The 21 `Bundle` doesn't have a version. Because of what we know about 2.1, we now know that we don't ever have to care about the `Bundle` `spec_version` value. I know everything I need to know on a per-object basis. For my implementations, I throw away the `Bundle` `spec_version`. It looks like @jordan2175  has done the same in [his implementation](https://github.com/freetaxii/libstix2/blob/master/objects/baseobject/baseObjects.go#L26-L29).

**Comment by StephenOTT** [comment]
:face_palm:  so in the new spec when you create a 2.1 object you need to apply the spec version identifier?!?

**Comment by varnerac** [comment]
Yes. I believe you’ll find it in the latest WD posted on the TC’s documents page. It’s a required property in 2.1.

**Comment by StephenOTT** [comment]
This is getting ridiculous. Going to be more "exceptions" then rules.  Libraries are going to be a mess of exception handling. Barrier to entry to new libraries seems to be growing rapidly with nuanced implementation details.....  :-1:

**Comment by jordan2175** [comment]
Where this will be an issue is when we do digital signatures.  I will leave this open and bump to a later release for review.

**Comment by jordan2175** [comment]
We talked about this on the working call on 2019-06-04 and decided that this was okay and that we needed some text to help people understand that is is okay to do.  John-Mark is going to add some proposed text in the document to address this.  When we do digital signatures this will not be a problem because we can simple say if the property is the same as its default value, then it must not be included in the canonicalization.

**Comment by jordan2175** [comment]
text was added.  Closing.

**Comment by jordan2175** [comment]
In section 3.6 the following text was added:

> If a property has the same value as the default, it MAY be omitted from a representation, and this does not represent a change to the object.
