### ISSUE TITLE
[2.1] Opinion Enum in 10.18 for Opinion SDO? Why not a Vocab?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#175]
in 10.18 there is a Opinion Enum: Why is this defined as a enum?  Where pretty much everything else in the spec is a open or closed vocab.

**Comment by ejratl** [comment]
The options in the enum capture one common way to express an opinion. Adding multiple conflicting ways of registering an opinion would make exchanging opinions more difficult. You can add a custom property to capture different forms of opinion. Do you have a use case for exchanging objects with opinions of different types in the same opinion property?

**Comment by StephenOTT** [comment]
Isn't the different ways to exchange opinions the same use case as the various ways to handle confidence ?  

I am only looking at the spec in terms of conformity at the moment as I go through a implementation for interop planning. The use of enum here is a on it's own impl where everything else is vocabs. Thus inconsistent.

**Comment by jordan2175** [comment]
Confidence is expressed by the content producer.  It is their confidence in their data.  Since 3rd parties can not modify existing data that they are not the producer of, then there needs to be a way for a 3rd party to express a similar or different view. This is done by generating an opinion object that is tied to the original through embedded relationships.

**Comment by StephenOTT** [comment]
Thanks
