### ISSUE TITLE
[2.1] Email Message SCO is valid with only the is_multipart property?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#182]
In section 6.6 all properties are optional except for `is_multipart`. 

The body and body_multipart fields have rules around usage based on the is_multipart. But the rule is "this property MUST NOT be used if is_multipart is true/false" 

Should this rule be updated to state that a body or body_multipart must be provided?   Or is a email message technically valid with just the common props and the is_multipart prop?

**Comment by rpiazza** [comment]
You might want to not include the body of the message (using either property).  For instance, you just want to share the To and Subject fields...

**Comment by StephenOTT** [comment]
@rpiazza, should it then be a rule such as: "at least one of the following fields must be provided..."

Can a email message only contain the the is_multipart property

**Comment by rpiazza** [comment]
@StephenOTT,

This seems to be a data quality problem.  I can make many nonsensical STIX objects based on the spec only.

**Comment by StephenOTT** [comment]
@rpiazza in section 6.7.6 WindowsTM PE Binary File Extension they seem to have accounted for this issue:

>An object using the WindowsTM​ ​PE Binary File Extension MUST​ contain at least one property other than the required ​pe_type​ property from this extension.

Where all properties are optional except for the single `pe_type` property.

**Comment by rpiazza** [comment]
I think this is slightly different.  Since *all* of the PRBinaryFile extension are optional, there is no purpose to having the extension in the first place unless there was at least one property, so it more of a "language" issue.

Anyway, In the EmailMessage there *is* always at least one property - is_multipart.

As I stated before, you can construct many different legal useless STIX objects, given the spec.  For instance, if the only property number_of_sections is populated, I'm not sure how useful that would be, but it would obey the normative statement you quoted.

**Comment by jordan2175** [comment]
The TC decided long ago that we could not be the data quality police. So as Rich mentioned, it is possible to produce STIX objects that do not make sense.  But you can not just start making things required.
