### ISSUE TITLE
[2.1] 6.12.4 Network Socket Extension: options property does not define what type the value is

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#185]
dictionary is defined as:

>Specifies any options (SO_*) that may be used by the socket, as a dictionary. Each key in the dictionary SHOULD​ be a case-preserved version of the option name, e.g., ​SO_ACCEPTCONN​. Each key value in the dictionary ​MUST​ be the value for the corresponding options key.

But the value's type is not defined in the description.  In other dictionaries, it defines what types are supported in the value.

Example of another dictionary:

>Each key in the dictionary ​MUST ​be the name of the header field and ​SHOULD​ preserve case, e.g., User-Agent​. The corresponding value for each dictionary key ​MUST​ always be a ​list​ of type string​ to support when a header field is repeated.

**Comment by StephenOTT** [comment]
Process: 6.13 has the same issue with `environment_variables` property:

>Specifies the list of environment variables associated with the process as a dictionary. Each key in the dictionary ​MUST​ be a case preserved version of the name of the environment variable, and each corresponding value ​MUST​ be the environment variable value as a string.

**Comment by StephenOTT** [comment]
Same issue in 6.13.2 Windows Process Extension

>Specifies the STARTUP_INFO struct used by the process, as a dictionary. Each name/value pair in the struct ​MUST be represented as a key/value pair in the dictionary, where each key ​MUST​ be a case-preserved version of the original name. For example, given a name of "lpDesktop" the corresponding key would be ​lpDesktop​.

**Comment by jordan2175** [comment]
I do not know the answer to this, I am guessing they did not define the type since they wanted you to be able to use what ever type of data it was originally.

**Comment by jordan2175** [comment]
We talked about this on 2019-11-12 @ikiril01 and @treyka will go and do some research on this.  We should also define the type of the value to be like string or number or something.

**Comment by jmgnc** [comment]
See: https://www.freebsd.org/cgi/man.cgi?query=setsockopt&sektion=2

most are integers, but there are a couple that are structures, in the case of the timeval ones, we should use the standard timestamp type.  The linger one will be a bit more complicated, as different operating systems may have different definitions, but likely common members.

**Comment by rpiazza** [comment]
As @jmgnc mentioned, all but three of the option's values are integers.  I'm not sure we can use the timestamp for S_SNDTIMEO and S_RCVTIMEO, since it is representing duration, not a moment in time.  We should probably say its the number of milliseconds, so it would also be an integer.

SO_LINGER is the only one what is problematic, because it specifies both the whether or not to linger, and for how long.  Perhaps a dictionary?

**Comment by jordan2175** [comment]
Could we also just say they are strings from a JSON perspective and then let people type cast them back to integers or floats or what ever in code?

**Comment by rpiazza** [comment]
If we want to interoperate - consumers would need to know how it interpret the string associated with SO_LINGER.  We could specify that, I guess.  In any case - I think it makes sense to say they are all integers, with the one SO_LINGER exception

**Comment by StephenOTT** [comment]
👍 for @jordan2175 proposal. Making them all strings simplified things.

Are there props that have multiple possible types?

**Comment by rpiazza** [comment]
Here is the text from the web:

All of the socket-level options except SO_LINGER, SO_RCVTIMEO and SO_SNDTIMEO, expect option_value to point to an integer and option_length to be set to the size of an integer. When the integer is nonzero, the option is enabled. When it is zero, the option is disabled. The SO_LINGER option expects option_value to point to a linger structure, as defined in sys/socket.h. This structure is defined in the following example:
struct  linger
{
        int     l_onoff;                /* option on/off */
        int     l_linger;               /* linger time */
};

The l_onoff field is set to 0 if the SO_LINGER option is begin disabled. A nonzero value enables the option. The l_linger field specifies the amount of time to linger on close. The units of l_linger are seconds.

**Comment by StephenOTT** [comment]
Okay so question: does it actually need to be a dictionary?  Seems fairly complex?  Any reason why this was not just a string value that someone can just their escaped object in?

**Comment by rpiazza** [comment]
Are you suggesting that the option property shouldn't be of type dictionary, but type string?

**Comment by StephenOTT** [comment]
I am asking if that makes more sense vs trying to map out the whole specialized dictionary.

**Comment by rpiazza** [comment]
If we say it is a dictionary - it will not need any special case parsing (except maybe for SO_LINGER) - since any implementation needs to know how to parse json dictionaries.  

Can you give an example of the string you have in mind - let's say there are three options (your pick :-) )

**Comment by StephenOTT** [comment]
I was just thinking single string field that has text indicating the content is to be a escaped Json object representing the same info that would be in the dictionary.  I guess I am asking: "what value does the property serve as a dictionary vs just a string with escaped json?"

**Comment by rpiazza** [comment]
Here is the list of uses of dictionaries in STIX

![image](https://user-images.githubusercontent.com/2091129/69014094-b104b500-0954-11ea-927a-977f9ec76b7b.png)

As we can see, we allow all different types for the values - mostly due to their corresponding real data.

I think we should just make sure that we specify the values for all dictionary keys be what they are in the real data - and handling that is passed on to the implementation.  Therefore, i think we should add the following text:

for hashes:
The value must be a string in the appropriate format defined by the hash type indicated in the dictionary key.

for options:
The value must be an integer.  If the dictionary key is SO_RCVTIMEO or SO_SNDTIMEO, the value represents the number of milliseconds.  If the dictionary key is SO_LINGER, the value should itself be a dictionary, with two possible keys:  enabled and linger_time.  The values allowed for both keys is an integer, where the linger_time is the number of milliseconds.

For startup info - things are a bit more complicated (see https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfoa).

DWORD	integer
LPSTR	string
LPBYTE	hex?
HANDLE  ?  - it seems like it is a pointer to one of the standard streams

Not sure what to say for this.

**Comment by jordan2175** [comment]
What I was saying above and people seemed to agree is that we just say the value portion for each key in a dictionary is a string.

**Comment by rpiazza** [comment]
That doesn't work for a number of reasons - some keys have more than one value - so you need a list of strings - you SHOULDN'T use duplicate keys in JSON dictionaries (its controversial if you should use duplicate keys - the JSON spec uses the SHOULD normative text).  I can see expressing integers as strings though....

When was it suggested that the value portion always be just a string?

**Comment by varnerac** [comment]
Nobody has mentioned making `options` its own object. We know the key names ahead of time. The values have different data types that we know ahead of time. It seems like the intuitive approach. It also maps well to other serialization strategies.

**Comment by jordan2175** [comment]
I really think that is what should happen @varnerac. If someone could put that together that would be great.   I am sure we could do this for a lot of other dictionaries as well.  Ideally, it would be super cool if we could just remove the whole dictionaries type.

**Comment by rpiazza** [comment]
The following text was added to the description of the option property:

Each dictionary value MUST be an integer.  For SO_RCVTIMEO, SO_SNDTIMEO and SO_LINGER the value represents the number of milliseconds.  If the SO_LINGER key is present, it indicates that the SO_LINGER option is active.

The three options called out concern elapsed time.  They are slightly different, but can all be generalized by using milliseconds.
