### ISSUE TITLE
[2.1] Process SCO: 6.13: Inconsistent usage of ID Contributing Properties and UUID

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#186]
6.13 for the Process SCO says:

>Since all properties on this object are optional, please use a UUIDv4 for the ID
of this object.

but description above says "A Process object ​MUST​ contain at least one property (other than ​type​) from this object (or one of its extensions)."  Therefore shouldn't there always be a property available?

Additionally this introduces a SCO that does not have a UUID v5.

I am assuming this was because it would mean that a extension dictionary property would have to be a ID contributing property?

**Comment by gjGatos** [comment]
The purpose of the UUID v5 is to allow for correlation of similar/same objects.  If people just used whichever property they wished in the Process object, then it could/would result in incorrect correlation.  It is therefore better that each object be generated with its own UUID v4 ID rather than having objects be generated with a UUID v5 ID that results in incorrect correlation.

**Comment by StephenOTT** [comment]
@gjGatos thanks for the details.  Where is that documented?  The spec states the v5 is used for recreating the id based on its content. If all properties are used then you can recreate the v5.  I did not suggest to use "whichever property they wished" 

Why is a Process different than other SCOs that have optionals?
