### ISSUE TITLE
file SCO is missing parent_directory_ref as an ID contributing property

### ISSUE THREAD

**Issue by chisholm** [oasis-tcs/cti-stix2#200]
Files with the same name and/or contents in different locations will have the same deterministic ID unless `parent_directory_ref` is also an ID contributing property.

I stumbled across this problem via a [MAEC document](https://github.com/MAECProject/schemas/blob/738694138744b890f0b1473eaaacff79169c40bb/examples/package_action_equivalency_example.json#L88) (it contains old STIX 2.0 style SCOs; see the SCO at the highlighted location and the one immediately below it).  It's basically saying that a malware creates a file with the same name in two different places.  That situation will be unrepresentable in STIX 2.1 with deterministic IDs unless this issue is fixed.

**Comment by rpiazza** [comment]
This email was sent to the cti list today:
Issue #200 concerns the problem of having two different File SCOs, with the same file name and/or contents (i.e., hashes and extensions or those properties are not present) but different parent_directory_ref property values.  Because parent_directory_ref is not one of the contributing properties used to compute the deterministic id – both File objects would have the same id – which is obviously not allowed.
 
The suggested solution is to include parent_directory_ref as one of the contributing properties for the File SCO.
 
The editors would like to make this change.  Please respond if you feel this change would be inappropriate.  If there is any objections, we can discuss them on the next working call.

**Comment by jordan2175** [comment]
parent_directory_ref was added to the list of deterministic ID contributing properties in section 6.7.1
