### ISSUE TITLE
Mismatch between common property "lang" and software property "languages".

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#227]
The common property "lang" has the following description:

>The lang property identifies the language of the text content in this object. When present, it MUST be a language code conformant to [RFC5646]. If the property is not present, then the language of the content is en (English).

The software property "languages"  has the following description:

>Specifies the languages supported by the software. The value of each list member MUST be an ISO 639-2 language code [ISO639-2].

These two language standards are slightly different.  The problem is that the basic form of RFC5646 is two characters, and the basic form of ISO639-2 is three characters.  

To avoid confusion, we should pick one standard for all language properties - preferably RFC5646, because two characters is more commonly used than three characters.

**Comment by jordan2175** [comment]
We talked about this on an editors call. If in software it is meant to be spoken languages, then we should have them be the same. Or was this meant to be programming languages that this was written in.  Need more information.

**Comment by jordan2175** [comment]
The description should match the lang property in 3.2 common properties or this should be an implementation language and match what is done in Malware.

**Comment by jordan2175** [comment]
Changed text to:
> Specifies the languages supported by the software. The value of each list member MUST be a language code conformant to [RFC5646].

**Comment by jordan2175** [comment]
Here is the background on this property from Ivan

> I believe the original interpretation of “human” language is correct. The original use case, from what I recall, is being able to describe software that may be released with support for different character sets; this can be useful in some instances where threat actors may target a specific software/character set tuple such as a Windows instance running a Japanese character set [1] (for example).
>
> [1] https://securityboulevard.com/2019/03/location-aware-malware-targets-japanese-and-korean-endpoints/

**Comment by allant0** [comment]
So I was interested in why there was a 3 letter variant of language standard defined. So I looked at this summary https://www.loc.gov/standards/iso639-2/php/code_list.php which lists all the languages supported by the 3 letter version that are *not* supported by the 2 letter version. 

So my question is this.

What happens if bad actors know that a threat intelligence global sharing language standard can't convey certain languages that are used? Would that might entice them to have conversion tools that communicate in those languages *explicitly* to make it hard for a TI product to convey that this is the language being used?

Auto-conversion of language is almost automatic. A bad actor could easily communicate in a language that isn't supported by the 2-letter variant and have auto-conversion on the start/end of communication into their native language.

Sound too far fetched? This is exactly what encrypted/ciphers do. So why would we make this mistake by limited to the 'common 2 letter variant' which is mostly because its not used for intelligence purposes.

I propose in this case the right choice for intelligence purposes is to use the 3 letter standard because it supports all languages and thats what the use case requirements demand.

**Comment by jordan2175** [comment]
The text already said a 2 digit code. We could change that, but that would probably be a material change. Are you suggesting that we need to make this change?
