### ISSUE TITLE
Request: Benign flag for vocab

### ISSUE THREAD

**Issue by iglocska** [oasis-tcs/cti-stix2#23]
As discussed on Slack, being able to mark Malware SDO objects as benign would allow the sharing of false-positive sandbox analysis results.

**Comment by ikiril01** [comment]
I support this idea. However, what we should name this vocabulary entry? Some options are:

* benign
* not-malicious
* not-malware

**Comment by jordan2175** [comment]
I support this too.  I would lean towards benign, but I can go either way.  Lets just make sure we do not need to create 3-4 options to capture the "not" or inverse state.

**Comment by JasonKeirstead** [comment]
I do not support this idea because it overlaps what I think is a much wider issue in being able to do this STIX wide. See https://github.com/oasis-tcs/cti-stix2/issues/22

**Comment by ikiril01** [comment]
@JasonKeirstead I understand your objection and classification object proposal (which I support). However, I think in this case we probably still need to add 'benign' or some similar label to the malware vocab, simply because labels are a required property on Malware. While I suppose you could use a custom value in such cases, having a standard way of classifying benign software that was sent to a sandbox (or other malware analysis) seems preferable.

**Comment by JasonKeirstead** [comment]
Isn't that going to be the same way to do things twice?

It seems it will make things more difficult for our consumers as now we have to look at two different values (which could contradict) to decide if something is benign.

Sent from IBM Verse


   Ivan Kirillov --- Re: [oasis-tcs/cti-stix2] Request: Benign flag for vocab (#23) --- 
    From:"Ivan Kirillov" <notifications@github.com>To:"oasis-tcs/cti-stix2" <cti-stix2@noreply.github.com>Cc:"JasonKeirstead" <jason.keirstead@ca.ibm.com>, "Mention" <mention@noreply.github.com>Date:Wed, Sep 13, 2017 5:43 PMSubject:Re: [oasis-tcs/cti-stix2] Request: Benign flag for vocab (#23)
  
  @JasonKeirstead I understand your objection and classification object proposal (which I support). However, I think in this case we probably still need to add 'benign' or some similar label to the malware vocab, simply because labels are a required property on Malware. While I suppose you could use a custom value in such cases, having a standard way of classifying benign software that was sent to a sandbox (or other malware analysis) seems preferable.

**Comment by johnwunder** [comment]
F2F: We need to support this capability, but the specific flag here is overcome by recent changes to how malware is being described.

**Comment by jordan2175** [comment]
benign was added to the AV Results vocab.  Does this address this?

**Comment by sbarnum** [comment]
I don't think this sort of adornment should go directly on the Malware object. It should be an external assertion regarding the Malware object in order to not change its state, to capture when such a determination was made, by who and with what level of confidence.
I do not believe that having "Benign" in malware type field/vocab makes sense.

**Comment by jordan2175** [comment]
We talked about this on the working call on 2019-05-28 and the discussion consensus was to life boat to WD05 or later and then look at this holistically.  Several people said this need to be done on many objects and not just malware.  Jason also said this should really be done via an assertion.

**Comment by jordan2175** [comment]
We talked about this on the working call on 2019-06-04 and decided to move this out to 2.2

**Comment by jordan2175** [comment]
We addressed this concern with the new Malware-Analysis object and Benign is listed in the Malware Result vocabulary.
