### ISSUE TITLE
Update JSON Reference

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-stix2#68]
STIX 2.0 references [RFC 7159](https://tools.ietf.org/html/rfc7159) for JSON. It was obsoleted by [RFC 8259](https://tools.ietf.org/html/rfc8259)

STIX 2.1 should reference RFC 8259. Additionally, RFC 8529 [changes course on Character Encoding](https://tools.ietf.org/html/rfc8259#section-8.1), moving away from non-UTF-8 payloads.

**Comment by johnwunder** [comment]
Updated text here: https://docs.google.com/document/d/1ShNq4c3e1CkfANmD9O--mdZ5H0O_GLnjN28a_yrEaco/edit#heading=h.vj2dopx186bb

Since we just followed the pattern already decided for TAXII, I'd suggest treating this as an editorial issue and skipping the discussion (we can list in changelog).

@varnerac can you review? https://docs.google.com/document/d/1ShNq4c3e1CkfANmD9O--mdZ5H0O_GLnjN28a_yrEaco/edit#heading=h.vj2dopx186bb

**Comment by johnwunder** [comment]
We reviewed on an editorial call, closing.
