### ISSUE TITLE
Allow modification of STIX object without versioning

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-stix2#77]
> Every representation (each time the object version is serialized and shared) of a version of an object (identified by the object’s id and modified properties) MUST always have the same set of properties and the same values for each property. In order to change the value of any property, or to add or remove properties, the modified property MUST be updated with the time of the change to indicate a new version.

This prevents modifications to an object even if it remains semantically unchanged.

I want to transform `artifact` `payload_bin` to `url`. This would mean that even if a producer sends it in as a `payload_bin`, consumers would get the object back with `url`. It's the same payload, just a different encoding.

If we allow multiple STIX versions in a single bundle, and legacy STIX 2.0 objects don’t have `version` fields, I’d like to explicitly add `version=2.0`

**Comment by jordan2175** [comment]
The editors have talked about this and do not understand exactly what you want to do here.  It seems like there is two different requests here.  We are going to move this to working draft 05.   Please add comments or notes here to give more details on what exactly you want or need changed.

**Comment by varnerac** [comment]
Sure. I can give you some examples to make it more clear. The `payload_bin` to URL is a bit of an extreme one.

Say I receive a STIX object without a `spec_version`. It’s implicitly `”2.0”`. Can I later return it as `”spec_version”: “2.0”`? It’s semantically the same, but not structurally. 

This also bumps into the “it’s a transport not a storage spec” idea and even issue https://github.com/oasis-tcs/cti-stix2/issues/148

Do I have to store the the string representation of the datetime stamp for fidelity or can I lose trailing zeroes?

There are obvious storage benefits of:

* not having to store the explicit lack of an implicit value
* Using native datetime storage types in databases

I’m not tied to the idea one way or another. I’m just curious if we plan on allowing multiple semantically equal representations of the same object.

**Comment by StephenOTT** [comment]
another good angle!

**Comment by rpiazza** [comment]
Hi @varnerac:

I think I understand the problem.  You receive a STIX 2.0 object, which doesn't have a spec_version property - you store it locally, and somehow mark it as being a 2.0 object.  Now you want to share it out - but because you can't version it (you aren't the owner) you have to remember exactly with properties were present when you received it because the spec says:

> Every representation (each time the object version is serialized and shared) of a version of an object (identified by the object's id and modified properties) MUST always have the same set of properties and the same values for each property.

The artifact example I think is different - just create a new object, and set up a relationship between the two (**derived-from** ?)

**Comment by varnerac** [comment]
@rpiazza I think we will make an exception for this on the new SCOs, where the properties could be on the object or on the parent Bundle or Envelope, right?

**Comment by jordan2175** [comment]
This is related to #150

**Comment by jordan2175** [comment]
We talked about this on the working call on 2019-06-04 and decided that this was okay and that we needed some text to help people understand that is is okay to do.  John-Mark is going to add some proposed text in the document to address this.  When we do digital signatures this will not be a problem because we can simple say if the property is the same as its default value, then it must not be included in the canonicalization.

**Comment by StephenOTT** [comment]
So to recap: this means that we are considering the objects equal: when a optional that has a default value is omitted, compared to the same object where the optional value is provided with the same default value?  Does this apply to the time stamps as well, where they provide less optional precision?

**Comment by jordan2175** [comment]
The objects are equal for default values.  For timestamps that is different since they represent significant digits.

**Comment by StephenOTT** [comment]
@jordan2175 was there text add for this?  As this relates to the whole conversation about if .100000000 vs .1 vs .100 all being equal in the context of time

**Comment by jordan2175** [comment]
In section 3.6 the following text was added: 

> If a property has the same value as the default, it MAY be omitted from a representation, and this does not represent a change to the object.  

This addresses the main issues raised in this issue and in #150.  However, this does not change the rules for timestamps.  12:20:51.1 is not the same as 12:20:51.100 nor is it the same as 12:20:51.100000 due to significant digits and the precision that the producer is able to do.  The TC decided to not have a separate property that defined the overall precision that the producer was using, and instead decided to just use the timestamps value.
